//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllocationCalculator.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AllocationCalculationsEntities : DbContext
    {
        public AllocationCalculationsEntities()
            : base("name=AllocationCalculationsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblLEA> tblLEAs { get; set; }
        public virtual DbSet<tblBasicAllocationPreviousYear> tblBasicAllocationPreviousYears { get; set; }
        public virtual DbSet<tblBasicAllocationSource> tblBasicAllocationSources { get; set; }
        public virtual DbSet<tblConcAllocationEligibility> tblConcAllocationEligibilities { get; set; }
        public virtual DbSet<tblConcAllocationPreviousYear> tblConcAllocationPreviousYears { get; set; }
        public virtual DbSet<tblConcAllocationSource> tblConcAllocationSources { get; set; }
    
        public virtual ObjectResult<Nullable<decimal>> BasicAllocation(Nullable<int> programYear)
        {
            var programYearParameter = programYear.HasValue ?
                new ObjectParameter("ProgramYear", programYear) :
                new ObjectParameter("ProgramYear", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("BasicAllocation", programYearParameter);
        }
    
        public virtual int ConcAllocation(Nullable<int> programYear)
        {
            var programYearParameter = programYear.HasValue ?
                new ObjectParameter("ProgramYear", programYear) :
                new ObjectParameter("ProgramYear", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ConcAllocation", programYearParameter);
        }
    }
}
