//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllocationCalculator.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBasicAllocationSource
    {
        public int AUN { get; set; }
        public Nullable<int> ProgramYear { get; set; }
        public Nullable<decimal> BasicAllocation { get; set; }
        public Nullable<double> TotalForumlaCount { get; set; }
        public Nullable<double> POP517 { get; set; }
        public Nullable<double> PercentageFormula { get; set; }
        public Nullable<int> CharterSchoolAdjustment { get; set; }
        public Nullable<double> BasicAllocationAfterCS { get; set; }
        public Nullable<int> HoldHarmlessRate { get; set; }
        public Nullable<decimal> HoldHarmlessAmount { get; set; }
        public Nullable<decimal> HoldHarmlessCheck { get; set; }
        public Nullable<double> LEAAboveHoldHarmless { get; set; }
        public Nullable<double> AdjustedLEAAboveHoldHarmless { get; set; }
        public Nullable<double> AllocationstoAllLEA { get; set; }
        public Nullable<double> FinalBasicAllocationAmt { get; set; }
        public Nullable<decimal> SumBasicAllocationAfterCS { get; set; }
        public Nullable<decimal> SumAdjustedLEAsAboveHoldHarmless { get; set; }
        public Nullable<decimal> SumLEAsAboveHoldHarmless { get; set; }
    
        public virtual tblLEA tblLEA { get; set; }
    }
}
