//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllocationCalculator.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBasicAllocationPreviousYear
    {
        public int AUN { get; set; }
        public Nullable<int> ProgramYear { get; set; }
        public Nullable<decimal> StateDeterminedFinalAllocationAmt { get; set; }
    
        public virtual tblLEA tblLEA { get; set; }
    }
}
