//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllocationCalculator.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblConcAllocationEligibility
    {
        public Nullable<double> AUN { get; set; }
        public string C_LEA_ { get; set; }
        public Nullable<double> Year2017 { get; set; }
        public Nullable<double> Year2016 { get; set; }
        public Nullable<double> Year2015 { get; set; }
        public Nullable<double> Year2014 { get; set; }
        public int ID { get; set; }
    }
}
