//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllocationCalculator.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblConcAllocationEligibility
    {
        public int AUN { get; set; }
        public string LEA { get; set; }
        public Nullable<double> PreviousYear1 { get; set; }
        public Nullable<double> PreviousYear2 { get; set; }
        public Nullable<double> PreviousYear3 { get; set; }
        public Nullable<double> PreviousYear4 { get; set; }
    
        public virtual tblLEA tblLEA { get; set; }
    }
}
