//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllocationCalculator.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMapCharterSchooltoSD
    {
        public Nullable<int> CSAUN { get; set; }
        public string CSAUNName { get; set; }
        public Nullable<int> AUN { get; set; }
        public string AgencyName { get; set; }
        public Nullable<double> NbrEnrolledStuds { get; set; }
        public Nullable<double> LowIncomePercentage { get; set; }
        public Nullable<double> FormulaStudents { get; set; }
        public Nullable<decimal> BasicAllocationPerPupilAmt { get; set; }
        public Nullable<decimal> ConcAllocationPerPupilAmt { get; set; }
        public Nullable<decimal> TargetedAllocationPerPupilAmt { get; set; }
        public Nullable<decimal> EFIGAllocationPerPupilAmount { get; set; }
        public Nullable<decimal> TotalSubtracted { get; set; }
        public int CID { get; set; }
    }
}
